### PR TITLE
Switched login flow to code authorization

### PR DESCRIPTION
**Pull request by adn77**
I adapted the login flow based on recent proxy intercepts and this:
  https://github.com/mkb79/Audible/issues/41

Fyi, I have zero knowledge of modern JS so please be gentle with any critism :D

### CODE REVIEW

**Comment by Apollon77** [comment]
Cool, thank you. Is also the token refresh working?

**Comment by volschin** [comment]
As I understand both methods are working at the moment. Could it be better to let choose the method by a switch?

**Comment by Apollon77** [comment]
All good this was not the question. It was about if the token refresh mechanismus is still working also when doing a new login with this method?

**Comment by adn77** [comment]
As this method returns a refresh_token, I believe the refresh is just the same. I'll test some more tonight.

Please review the code, especially the parts deleted... I didn't quite understand all the callback stuff ;)

**Comment by Apollon77** [comment]
> Please review the code, especially the parts deleted... I didn't quite understand all the callback stuff ;)

Will also try to find time tonight

**Comment by adn77** [comment]
access_token refresh works:

`POST /auth/token HTTP/1.1
x-amzn-identity-auth-domain: api.amazon.de

app_name=ioBroker Alexa2
app_version=2.2.223830.0
di.sdk.version=6.10.0
di.hw.version=iPhone
di.os.name=iOS
di.os.version=11.4.1
package_name=com.amazon.echo
platform=iOS
current_version=6.10.0
requested_token_type=access_token
source_token_type=refresh_token
source_token=Atnr|...`

I don't quite understand what the access_token is used for. I can always use the refresh_token to retrieve the cookies:
(There seems to be a change for the exchangetoken endpoint)
`POST /ap/exchangetoken/cookies HTTP/1.1
x-amzn-identity-auth-domain: api.amazon.de

requested_token_type=auth_cookies
app_name=Amazon Alexa
app_version=2.2.223830.0
di.sdk.version=6.10.0
domain=www.amazon.de
source_token_type=refresh_token
source_token=Atnr|...`

Note: no cookies were required when making the request!

That leaves the renewal of the refresh_token... unless it never expires.

**Comment by Apollon77** [comment]
Thnak you for checking!

**Comment by Apollon77** [comment]
Changes make sense ... thank you, I will merge now and release as new version next days

**Comment by Apollon77** [comment]
@adn77 BTW I made the refresh flow working with both in the end ... lets see how it goes midterm.

I'm not that sure that code-verieir and auth.code is working "long time"

**Pull request merged**
